// ... existing code ...
// Example if it's in a string
const priceText = "R{amount}"; // Changed from ₹ to R
// ... existing code ...

// If used as a variable prefix (uncommon but possible)
const Rprice = 100; // Changed from ₹price
// ... existing code ... 